const quotes = [ 
    "I have back problems, I know, I’m a grandpa - Samik 2023",
    "Don’t you agree that Danny is spicy 🥵 - Samik 2023",
    "I coached my yr 5 friend last year through 4 boyfriends and 4 break ups - Lilian 2023",
    "Angela chair guy - Aanya 2023",
    "Like I spawned and everyone was like sAmIkKkKkK!!! - Samik 2023",
    "I got an A? SHEEEEEESHHHH! - Kerui 2023",
    "Danny was called sonic the hedgehog - Lola 2023",
    "#SELF LOVE - Lola 2023",
    "Oh you wanna go kid? - Lilian 2023",
    "I’m confuzzled - Kerui 2023", 
    "Lola dreams that Samik licks her toes - Kerui 2023",
    "Kerui is way too messed up - Everyone",
    "I am not innocent, I do know stuff - Kerui 2023",
    "Stop saying that! I copyrighted it - Lilian 2023",
    "I won’t tell piss - Lilian 2023",
    "a Hee hee heee heee ha ha ha aha heee haha - Samik 2023",
    "I LIKE BALLS - Lukas 2023",
    "I like holding balls - Danny 2023",
    "我喜欢吃球 (I eat balls) - Kerui 2023", 
    "It’s white, sticky and tasty - Ming Lang 2023",
    "我喜欢吃大屁股 - Mehrad 2023",
    "My name is Terry! not Kerui! - Kerui 2023",
    "Guys, I deeply do not care whatsoever if I have roasted u abt ur height. If u felt like this has or will offends u as a joke, pls sthu and know that u r a potato - Samik 2023",
    "Y in da kangaroos… - Samik 2023",
    "OMG NO!! MY GPA IS AT 14.56 BECAUSE I GOT AN A!!!! - Sophie 2023",
    "I was so bad cos I went first… I got 90/100 😭 - Sophie 2023",
    "NOOOOO MY GPA WENT DOWN 0.17 POINTS!!! - Dylan 2023",
    "And I’m chilling here with my 13.5 GPA :D - Lilian 2023",
    "SAY THAT AGAIN AND I WILL MURDER YOU SO BAD THAT YOU WON'T EVER BE BLIND AGAIN. YOU’LL BE FREAKIN DEAD - Lilian 2023", //30
    "YOu KnoW WhAT THaT souNDS liKe? A YOU PROBLEM! - Mostly Lilian. but also nearly everyone in 700 2023",
    "TOFFEE IS DA BEST - Lilian 2023",
    "My hair just sticks up - Yiming",
    "#itspanglangnow - Sophie 2023",
    "Nope. No. Fine… maybe. Nah… - Sophie 2023",
    "Short people always rage quit lol - Lilian 2023",
    "OMG I’m gonna fail!!! *gets A+* - Everyone in Ignite 2023",
    "你不是我的好朋友 - Google Translate 2023",
    "我会送你去见耶稣 - Google Translate 2023", 
    "I only see one capybara out of like sex - Lilian 2023",
    "Oh sh... - Lilian 2023",
    "So hopefully he will fix the white issue - Dylan 2023",
    "ThAtS whAT shE sAId! - Ming Lang 2023",
    "Stop swearing! - Kerui 2023",
    "ITS LILIAN HERE AND I SAY BALLS ARE NOT TASTY - Lilian 2023",
    "Yes sire! - Ming Lang 2023",
    "Dylan I hate you! - Kerui 2023",
    "You are so annoying - Kerui 2023",
    "Idk? I know what idk means! Idk why but I will keep saying idk - Kerui 2023", 
    "*Dies when someone says aaHAna* - Aahana 2023",
    "*Exaggerated double eyebrow raise* - Ming Lang 2023",
    "That’s racist - Samik 2023",
    "You’re such a pastry - Samik 2023",
    "Kerui is like my emotional support animal - Samik 2023",
    "Y’all sweats - Samik 2023",
    "*Insert huge essay here* - Dylan 2023",
    "Danny’s such a baddieeeee - Aanya 2023",
    "TRAIIIITORRRRRRRRRRRRRR - Oliver 2023",
    "MAGENTAAAAA - Oliver 2023", 
    "iF yOu sPeLl ApPlEsAuCe, WiTh JuSt A’s, tHeN yOu GeT AAHHHHHHHHHHHH - Oliver 2023",
    "Excuse my pro speeling and grammartation skillz - Lilian 2023",
    "Why doesn't anyone believe that I didn't study for Ignite?! - Jesper 2023",
    "A pastry no greater hath I seen - Samik 2023",
    "Whaaaaaaaaaaaaaaat? - Kerui 2023",
    "*Dies after seeing 688 one more time* - Kerui 2023",
    "Stop playing the mind-numbingly boring road car game! - Everyone to Lukas",
    "Coding this was PAAAAAIIIIINNNNNN! - Kerui 2023",
    "GUYS! ITS A WILD MEHRAD! TAKE A PIC QUICK 📸 - Lola 2023",
    "I’m proud of my B - Linuka 2023", 
    "Be scared of Samik, he's short - Lola 2023",
    "CAN'T BEAT MY 2,1 MUDDA QUACKERS - Samik 2023",
    "Lola: 👹👹👹, Samik: Why are you spamming pics of Mehrad?",
    "Bro... - Samik 2023",
    "Nahhhhhh (sarcasm) - Linuka 2023",
    "Tut tut tut tut tut *sigh*, very disappointed in you -Tyler 2023",
    "Apologies - Tyler 2023",
    "The madman, he did it - Dylan 2023",
    "MEANIE BOMBINIE - Lola 2023",
    "Bro got comebacks from wattpad - Lilian 2023",
    "ChIlL DaH MoOlAH KiDs - Lukas 2023",
    "I am very sorry for the sin I have commited - Samik 2023",
    "Did *someone in 700* say *something sus and definitely not something they said*? - Ming Lang 2023",
    "Did someone just say my name? - Ming Lang 2023",
    "Hopefully I wont get murdered today... Like... I guess there is a chance that I wont die... *gets murdered one second later* - Kerui 2023",
    "I love being annoying - Kerui 2023",
    "I'm not tall, your just short - Tyler 2023",
    "I have been accused of liking 6 different people in the past week :(, has it become a meme at this point to annoy me? - Kerui 2023",
    "We are in year 7! Not Year 12! - Kerui 2023",
    "Year 7 is a good year to date - Isabelle 2023",
    "That's BuLlYiSm! - Everyone in 700 2023",
    "Stop it, I don't like it! - Everyone in 700 2023",
    "I hate Kerui. He plays a bad instrument - Jesper 2023",
    "Jesper is lazy, selfish, stupid and single-minded - Kerui 2023",
    "Oh no! Whatever shall I do - Dylan 2023",
    "After a long while being in the same class, still no one asked. - Ming Lang 2023",
    "But I didn’t ask about you not having asked! - Oliver 2023",
    "*Howling like a monkey* - Oliver 2023",
    "Bo’lle o’ wa’er - Kerui 2023",
    ]; 
